###########################
# LedBox Definitions
###########################

# all lengths are in mm

GRID_W = 18
GRID_H = 13

THICKNESS = 2

GRID_PART_WIDTH = 30 # - THICKNESS
GRID_PART_HEIGHT = 30 # - THICKNESS

PIN_SIZE = 10
PIN_WIDTH = THICKNESS

WIRE_DIP_SIZE = 10
WIRE_DIP_WIDTH = THICKNESS

LIP_WIDTH = THICKNESS

BOX_INNER_DEPTH = 30
BOX_OUTER_DEPTH = BOX_INNER_DEPTH + (2 * THICKNESS)

DIVIDER_HEIGHT = BOX_INNER_DEPTH
HORIZONTAL_DIVIDER_COUNT = GRID_H - 1
VERTCAL_DIVIDER_COUNT = GRID_W - 1

VERTICAL_DIVIDER_LENGTH = (GRID_PART_HEIGHT * GRID_H) + ((GRID_H - 1) * THICKNESS)
HORIZONTAL_DIVIDER_LENGTH = (GRID_PART_WIDTH * GRID_W) + ((GRID_W - 1) * THICKNESS)

SLID_DEPTH = DIVIDER_HEIGHT / 2
SLID_WIDTH = THICKNESS

BOTTOM_MARGIN = 30	# Not used for now
